### ISSUE TITLE
Packaging motis for Linux Distributions

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis#196]
Just updated to the current release and wondered about packaging motis would be an improvement or not. Did you already though about this? E.g. if I setup a web server I usually get e.g. apache web server it from the repository as well, why not mtois.

Pros I came up with:
- easy updates without the need of manual intervention
- easy accessible for users who want to give it a try
- raise some awareness about motis

Don't think this is a primary issue, but wondered whether you already thought about it.

**Comment by felixguendling** [comment]
Yes, ideally we could have something like [vectorized](https://vectorized.io/) on their landing page with "Try Redpanda today" + 1-step copy&paste installation for all major supported platforms. This would require at least a deb and rpm package. Since 'deb' packages are easier to handle and from what I heard Debian-based distributions are more common, I would start with a deb package.

It should probably contain:

  - scripts to add (on install) a `motis` user and group
  - scripts to remove (on uninstall) the `motis` user and group (not sure about that - what about files that are still owned by the motis user?)
  - a systemd service `/etc/systemd/system/motis.service`
  - a systemd restart service `/etc/systemd/system/motis-restart.service`
  - a systemd restart timer file `/etc/systemd/system/motis-restart.timer`
  - maybe a systemd update service+timer for realtime updates - this part will be moved into MOTIS ('ris' module) in the future

Maybe it's an option to use CMake deb support: https://cmake.org/cmake/help/latest/cpack_gen/deb.html

It seems to be possible to host deb packages using GitHub pages: https://pmateusz.github.io/linux/2017/06/30/linux-secure-apt-repository.html

Currently, this is not something anyone is working on. Feel free to contribute packaging + package hosting.
