### ISSUE TITLE
Docker input schedule directory differences in documentation

### ISSUE THREAD

**Issue by mariodavid** [motis-project/motis#212]
Hi,

I have one question about running motis via docker. In the [Dockerfile](https://github.com/motis-project/motis/blob/master/Dockerfile#L15) I see that by default it suggests putting the schedule sub-directory into the `input` directory:

```
[import]\n\
paths=schedule:/input/schedule\n\
```

In [this comment](https://github.com/motis-project/motis/issues/181#issuecomment-993541774) from @felixguendling, it suggests downloading the schedule data into the `/data` directory:

```
SCHEDULE_URL=https://opentransportdata.swiss/dataset/55b617c1-7241-4254-b243-0352d5523f6f/resource/54262e6d-04df-4d7d-bdb2-b6d173a49d0a/download/4_tu_ch_oev_sammlung_ch__2021_20211208_201836.zip

#...
mkdir -p motis-swiss/data/hrd

#...

# Download and unpack timetable.
wget $SCHEDULE_URL
unzip 4_tu_ch_oev_sammlung_ch__2021_20211208_201836.zip -d data/hrd


# Write config.ini
echo "\
#...

[import]\n\
paths=schedule:data/hrd\n\
# ...
```

This is in alignment with the official [installation documentation](https://motis-project.de/docs/install) from:

```
Download the latest dataset HAFAS Rohdaten (version 5.20.39 - “Timetable 202x (HRDF)” not version 5.40) dataset from [opentransportdata.swiss](http://opentransportdata.swiss/en/dataset) and extract it into your data/hrd folder.
```

But in the [announcement](https://motis-project.de/release/2021/09/11/motis-tools-release.html) from 09-2021 it says, that the input directory can now be used for read-only input data (like schedule).

I think I just do not have the full understanding of what the `schedule` directory is and how it should be treated.

It would be great if you can help me out here on where to put the schedule information.

Thanks
Mario

**Comment by felixguendling** [comment]
First of all thank you for trying out MOTIS and for giving feedback!

Sorry, the way to deploy MOTIS with docker is not very well documented. I plan to add a separate section about Docker deployment to the MOTIS documentation on motis-project.de.

You're mixing two things:

  - running MOTIS with a single binary (*without* Docker):
    - the current documentation on motis-project.de
    - [the installation script](https://github.com/motis-project/motis/issues/181#issuecomment-993541774)
  - running MOTIS with Docker

Both cases work with just one folder (the "data" directory) - or you can split the data directory:

  - input data that read-only (like the timetable data or the OSM file)
  - data that is generated by MOTIS (read/write):
    - logs
    - preprocessed data
    - databases (e.g. for real-time update data)

The version where you have two separate directories is especially useful for Docker, because then the container does not require write access to a volume that's mounted from a host directory. We are deploying our MOTIS instances this way but it is not mandatory.

After all, both options work perfectly fine. The only difference is whether you use `import.paths=schedule:input/...` or `import.paths=schedule:data/...` etc.

Version 0.5 is the first version where MOTIS does not write anymore to the schedule timetable folder which enables this change. But this does not mean that you need to make use of it. The version in the documentation on motis-project.de and in the script still works.

**Comment by felixguendling** [comment]
Maybe the documentation should only explain the version with split (input=read-only, data=read-write but internal volume not mounted to the host) to avoid confusion - even if putting everything in the same folder would still work.

**Comment by mariodavid** [comment]
hi @felixguendling,

thanks for the fast response. Ok, got it. Sounds reasonable. Then I will go with the `/input` volume as well.

> The version where you have two separate directories is especially useful for Docker, because then the container does not require write access to a volume that's mounted from a host directory. We are deploying our MOTIS instances this way but it is not mandatory.

So you mean you put the `/input` volume as read-only and mount it from in the docker host (or [EFS](https://aws.amazon.com/efs) volume in my case) and the `data` volume does not actually need to be mounted, correct? 

Does that mean that there is no way to cache these initial calculations that happen during container startup? I was hoping that the container would startup first and perform those calculations, but by externalizing the `/data` directory to an EFS volume this calculation only happens for the first container instance.

But with your description, that you don't externalize the `/data` volume, I guess this is not how it works, correct?

**Comment by felixguendling** [comment]
We use one read-only `bind` volume for `/input` and one `volume` for `/data`.

```yaml
volumes:
  - type: bind
    source: ./data
    target: /input
    read_only: true
  - type: volume
    source: data-volume
    target: /data
```

The `volume` is still persistent and will be re-used by the container to prevent that the preprocessing needs to be repeated.

I haven't tried running MOTIS on AWS with Kubernetes. So unfortunately, I cannot help much with this. Feel free to share your setup. I would be happy to put a how-to on motis-project.de or the GitHub wiki page.

**Comment by mariodavid** [comment]
> The /data volume is still persistent and will be re-used by the container to prevent that the preprocessing needs to be repeated.

ok, that sounds good 👍. I also tried it out locally and in fact, the second start is way faster.

I think there are not a lot of AWS specifics in here, besides the fact that for Fargate it probably requires a dedicated volume mounting also for the `/data` directory, since there is no guarantee that the next container will actually start on the same host, but I will let you know once I got it up and running :)

**Comment by felixguendling** [comment]
With v2 the setup should be very simple: `motis import` generates a data directory and `motis server` runs from this data directory.
