### ISSUE TITLE
Upgrade to 0.8.6: [VERIFY FAIL] some imports were not successful: gbfs

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis#271]
Hi,
I just wanted to upgrade our motis-instance to the newest release, so I replaced the old motis version with the latest release (0.8.6) from 0.7.5. Now when I try to execute it as usual (`sudo ./motis/motis`) it does fail with the following error:

```
     address: FINISHED
         csa: FINISHED
        gbfs: WAITING: {"OSRM_FOOT"}
   osrm-bike: FINISHED
    osrm-bus: FINISHED
    osrm-car: FINISHED
     parking: FINISHED
        path: FINISHED
      paxmon: FINISHED
         ppr: FINISHED
    schedule: FINISHED
       tiles: FINISHED
   tripbased: FINISHED
2022-08-15T08:15:51Z [VERIFY FAIL] some imports were not successful: gbfs

initialization error: some imports were not successful: gbfs

```
I saw that version 0.8 introduced experimental GBFS support, but I wasn't aware that I would need to change my data or provide additional configuration in the config.ini. I could also not found any information on the release page or in the GitHub Wiki regarding this issue. As we currently don't need GBFS a quick workaround would be to set a config to deactivate GBFS, but in my opinion it at least be mentioned in the release log, that manual intervention is needed when updated (if that's the case and it isn't a issue on my side).

**Comment by felixguendling** [comment]
The GBFS module requires the OSRM foot routing profile to be enabled. Disabling the GBFS module is the right thing to do in this case.

I think it makes sense to put a general advice in the documentation to always explicitly specify a the list of enabled modules manually in the `config.ini`. Otherwise, it will happen again and again when upgrading MOTIS that newer versions will add modules (which are enabled by default without this explicit list of enabled modules) which have new requirements (new input data, etc.) that are not met with the `config.ini` from the previous version.

So every `config.ini` should probably start with a list of modules like this:

```ini
modules=intermodal
modules=tripbased
modules=ppr
modules=parking
modules=osrm
modules=lookup
modules=railviz
modules=address
modules=guesser
modules=routing
modules=path
```

Of course, this list depends on your needs and should be adjusted accordingly.

**Comment by 1Maxnet1** [comment]
> Disabling the GBFS module is the right thing to do in this case.

Thanks for the quick answer. How would I disable GBFS-Support ?

**Comment by felixguendling** [comment]
If you do not list the `gbfs` module, it's disabled. As shown in the example above.

**Comment by 1Maxnet1** [comment]
> If you do not list the `gbfs` module, it's disabled. As shown in the example above.

Ah got it. Yeah that worked for me. So the issue is resolved on my side. You can keep it open to keep track of the documentation improvements, else feel free to close it. I could also offer to open a PR with a proposal for the documentation, but this might take some time, until beginning of September.

**Comment by felixguendling** [comment]
I removed the setup instructions from motis-project.de (@motis-project/motis-page repo) and wrote a new setup how-to here: https://github.com/motis-project/motis/wiki/Installation-and-Setup

Currently, this does not include:

  - real-time setup
  - multi-schedule setup
  - windows version of the how-to

I will try to extend these instructions as I find time.
