### ISSUE TITLE
Availability of MOTIS-App outside of Google Play Store

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis#391]
Currently when someone (like me) wants to use the MOTIS Android App, one needs to retrieve it from the Google Play Store. However as far as I understand e.g. https://github.com/motis-project/motis/pull/387/files the code at least is open source.
So would it be possible to make the app usable without the Google Play Store?
Some options I consider:
1. Offer some documentation how to build it yourself: Makes sense in general for development, but not very feasible for end-users.
2. upload the APK to releases: offers end users to download the APK. Not ideal but would also allow Third-Party F-Droid repositories to offer the APK for end-users to download and update.
3. Submitting to F-Droid Repository: This would easily allow to install the App for users of F-Droid, however there are a bunch of criteria to be met.

Any thoughts on this?

**Comment by felixguendling** [comment]
About your points:

1. Building should be: "Open Android Studio on `ui/android`".
2. That would require to automate the Android build with GitHub Actions. Currently not planned, but PRs are welcome.
3. If someone would want to do this (APK can easily be generated - see (1)), this would be great.

I'm not really happy with the Android app. For several reasons:

  - design is outdated (Material Design 2 instead of Material Design 3)
  - code is outdated (Java + old widgets instead of Kotlin + JetPack Compose)
  - It showcases only a very very small part of the backend functionalities (not even coordinate -> coordinate search!) which is dangerous because people interested in MOTIS might think, that this is all MOTIS has to offer.

Another problem in general with the frontends (Android, web) is, that currently we do not have enough developer capacity to maintain backend and frontends in all areas on a high level. And if we give up something, it's obviously the frontends. So currently, I consider the frontends (app and web) in "maintainance mode". We still need them to showcase MOTIS but we cannot put a lot of effort into them, because our focus should be on the backend.
