### ISSUE TITLE
Nigiri routing doesn't generate foot transfers

### ISSUE THREAD

**Issue by dvdkon** [motis-project/motis#398]
Hi, I'm trying to use MOTIS to route on a [GTFS feed of Czech public transport](https://data.jr.ggu.cz/results/2023-09-20/JDF_merged_GTFS.zip) that I created. Due to the size of the feed, I wanted to use the new nigiri module. Routing seems to work well, except for one issue: no foot transfers are ever used. They are generated on the [public demo site](https://europe.motis-project.de), so I assume this is specifically a nigiri problem.

For example, trying to plan a route from "Praha,Můstek" to "Brno,ÚAN Zvonařka" on 2023-09-21 will find a 9:32 route that uses a long detour to avoid a short foot transfer from "Praha,Florenc" to "Praha,ÚAN Florenc". Manually placing the from/to pins on those stops' locations generates a foot-only route, so the Valhalla routing is working.

This is also a problem for "last-mile" foot transfers when the destination is a stop: routing to "Praha,ÚAN Florenc" directly also only gives routes that use detours instead of going on foot from "Praha,Florenc". The correct route is generated when the destination is a map pin. I'm not sure if this is intended behaviour.

I had to increase `kMaxDays` in  `deps/nigiri/include/nigiri/types.h` to 16384 since my GTFS batch nominally covers a very long time period. I'll come up with a better solution later.

My config file:
```
modules=nigiri
modules=intermodal
modules=valhalla
modules=tiles
modules=address

[server]
static_path=../ui/web
[import]
paths=schedule-czjdf:input/schedule/JDF_merged_GTFS
paths=osm:input/osm/czech-republic-latest.osm.pbf
[dataset]
no_schedule=true
[nigiri]
first_day=TODAY
num_days=7
lookup=true
railviz=true
guesser=true
routing=true
[intermodal]
router=nigiri
[tiles]
profile=../deps/tiles/profile/background.lua
```

**Comment by felixguendling** [comment]
I am not sure, if I understood the problem 100%. The current version has two sources of footpaths:

- For stop-to-stop footpaths:
  - All timed transfers from the `transfers.txt` file are considered with their exact times (rounded to minutes)
  - All stops with a distance below `nigiri.link_stop_distance` (default = 100 meters) are connected by footpaths
  - Footpaths are created transitively. So if a footpaths `A->B` and `B->C` exist, then `A->C` is created if it does not exist yet.
  - Valhalla/OSRM are *not* used here.
- For coordinate-to-stop or stop-to-coordinate (first and last leg), the router specified in the query options is used (PPR / OSRM / Valhalla / GBFS).

So your experiment of placing from/to pins on the stop locations does not imply that the stop-to-stop footpath exists in your dataset (or those stops have a beeline distance below `nigiri.link_stop_distance`).

@carstenhagelgans is working on changing this, so the footpaths between stops can be computed using Per Pedes Routing (PPR) - see https://github.com/motis-project/motis/pull/373. After this PR is merged, there will be an option to replace the information contained in `footpaths.txt` with footpaths calculated by PPR.

I will work on a fix for the `kMaxDays` problems in October. The problem is that the parser uses the bitfields to map the GTFS timetable with its entire period (first bitfield day = first GTFS timetable day). If we change this to "first bitfield day = `nigiri.first_day`", this problem should be solved.

I assume the Czech feed you posted is public? Is there a static link that always references the latest dataset so I can add the feed to [europe.motis-project.de](https://europe.motis-project.de)?

**Comment by dvdkon** [comment]
Thank you for the reply. I didn't realise that footpath transfers are computed separately and only in a specific radius. Increasing `nigiri.link_stop_distance` gave the results I expected. I'm happy to see that work is underway to improve this further.

The feed is public, as is the [software](https://gitlab.com/dvdkon/jrutil) used to generate it. It's currently very WIP, I only got a valid feed a few days back. When it's a little more stable, I'll create a stable link and send it to you.

**Comment by felixguendling** [comment]
Thank you very much for providing the data + software! Looking forward to embed it into europe.motis-project.de! :sunglasses: 

I'll ping back here when I have a fix for the `kMaxDays` problem. It will take a few weeks.

**Comment by dvdkon** [comment]
I just tried loading the data into the latest version of MOTIS and I can report that it loaded without any patches needed.

Adding the `transfers` module (and also `ppr` it depends on) fixed my issues with foot transfers too. Thanks!

The Czech feed is sadly still experimental, but I did at least create [a stable URL](https://data.jr.ggu.cz/results/latest/) (see `CZPTT_GTFS.zip` and `JDF_merged_GTFS.zip`) and started my own [testing MOTIS instance](https://motis.jr.ggu.cz/). If you aren't worried about data accuracy (the source has small issues), I think it's good enough to be used as part of a test suite.
