### ISSUE TITLE
Use the demo web app with a custom tile server

### ISSUE THREAD

**Issue by laem** [motis-project/motis#428]
I see that generating tiles with the tiles module is a good part of the setup times of Motis. 

I'm not yet interested in providing my own tile server. How could I use e.g. maptiler ? 

I see the option 
```
--railviz.tiles_redirect arg          http://url.to/tiles/server (empty: use 
                                        this MOTIS instance)
``` 
but wasn't able to make it work with the link to a maptiler style.json.

**Comment by felixguendling** [comment]
`--railviz.tiles_redirect` refers to a URL that delivers the actual tiles (including `{x}/{y}/{z}` as placeholders for the positions). Something like `https://tile.openstreetmap.de/{z}/{x}/{y}.png` (not sure if this would work, because we're currently using vector tiles).

To replace the actual map style, you would need to change the code here (I'm not an expert for this topic):
https://github.com/motis-project/motis/tree/master/ui/web/js

**Comment by felixguendling** [comment]
> I see that generating tiles with the tiles module is a good part of the setup times of Motis.

Considering you only do it once (since map data rarely changes), this has never been an issue for us. The first run takes a bit longer, but after that it takes zero seconds to boot.

Since in your setup you seem to delete all the data `rm -rf config.ini motis* data/*`, it takes a long time. But if you would keep the `data` folder or at least in this case the `data/tiles` directory, the startup time would be negligible. I would recommend to keep the `data` folder always.

**Comment by laem** [comment]
> Since in your setup you seem to delete all the data rm -rf config.ini motis* data/*, it takes a long time. But if you would keep the data folder or at least in this case the data/tiles directory, the startup time would be negligible. I would recommend to keep the data folder always.

Thanks ! That's indeed key. I haven't delved yet in this folder.

**Comment by laem** [comment]
Hi @felixguendling, I had time to try to use the option `--railviz.tiles_redirect` with a maptiler URL. 

`https://api.maptiler.com/maps/dataviz/{z}/{x}/{y}.png?key=MYKEY`

But the web app fails to load tiles. 

![image](https://github.com/motis-project/motis/assets/1177762/a602611a-d47b-468e-9e1b-d76f5bf64999)

Looks like it's trying to use the `tiles` module, that I deactivated on purpose. Should I add the tile module in the config but put some special argument in the [tiles] section to make it redirect to my custom url ?

**Comment by felixguendling** [comment]
There are more tiles requests that are supposed to fail unless you have the path module and the gbfs module running. For both, you will see failing requests unless the module is active.

I'm also pretty sure that the map style would not fit to your vector tiles anyway.

I think if you really want to make frontend changes, you would need to go deep and start programming on the web user interface code.

Since we don't have the capacity to maintain the frontend and I don't see a future for the Elm code (as Elm is more or less discontinued), I consider the current frontend version as deprecated. We just started another project where we'll need a frontend anyway but it will take some time until there's a usable replacement available.

**Comment by laem** [comment]
Thanks, that's clear. Well, that's what I'm building, a front-end 😅 (in NextJs). But using the default one was useful to check at a glance that motis loaded with the good GTFS data. 

The "realtime" buses location is cool to check that, but I haven't yet found a way to make it useful for the end user on the interface. 


![image](https://github.com/motis-project/motis/assets/1177762/544e2226-4bb9-4765-8763-4b457b183ef5)
![image](https://github.com/motis-project/motis/assets/1177762/a5e6fd35-d5b5-4aab-906a-57cbbfa79980)

Closing this issue then.
