### ISSUE TITLE
Intermodal bus + boat request not working

### ISSUE THREAD

**Issue by laem** [motis-project/motis#434]
I've added some GTFS in Brittany that give access to island connections by boat. I'm happy to see that they work from port to port. 

But when I'm trying to plan an intermodal route that brings the user from somewhere in the city (A) further from the port (B), to the island (C), Motis fails. 

You can try the requests on my instance : https://motis.cartes.app. 

This is quite surprising since the route from A to B returns lots of buses (+ walk) in less than one second. 

![image](https://github.com/motis-project/motis/assets/1177762/d3153cd4-cb68-410e-bc86-e5bb4e537f9e)

Then, from the port (B, but A on the following capture) to the island (C, but B on the following capture), it works too in less than 2 seconds. 
![image](https://github.com/motis-project/motis/assets/1177762/f93b515d-4acc-455d-8f86-831572834968)

Going from A to C returns nothing and takes quite some time. 

![image](https://github.com/motis-project/motis/assets/1177762/69f4e150-63be-4d65-951e-3308e10075a4)

Is there a request parameter (not active by default in the demo app) that I'm missing to enable this bus - boat intermodal routing ?

**Comment by felixguendling** [comment]
I'm not sure, if I understand your test case. I understand it's a journey A->B->C. Can you please give exact coordinates for A, B and C that I can copy & paste into the MOTIS UI?

With my limited understanding of your test case: it looks like there is a walk required at B, so it is probably not just B but B1 where you arrive and B2 where you depart with the next trip. If B1 and B2 are not linked explicitly (which is definitely the case if they are from different GTFS datasets), it depends on the maximum distance between stops where `nigiri` (I guess you use the new core?) links stops. One parameter you can try to increase is `nigiri.link_stop_distance`.

Another parameter which is currently hardcoded and cannot be configured at runtime is this one:
https://github.com/motis-project/nigiri/blob/166411ed9e80347a5b51a34150dc11bda44f3c03/src/loader/build_footpaths.cc#L212

Can you please check if there's B or actually B2 and B2 and if there are B1 and B2 what's the distance B1, B2 (direct line distance) and are they from different datasets (which is important because for different datasets the hardcoded variable is relevant for those from the same dataset the configation variable `nigiri.link_stop_distance`)? If they are from the same dataset, you might check if there's a footpath given in `transfers.txt` and whether the time given there is sufficient to make the transfer (difference between arrival and departure).
