### ISSUE TITLE
Web UI shows truncated times with just minute part for long journeys

### ISSUE THREAD

**Issue by mlundblad** [motis-project/motis#450]
I tried searching for a trip from Brussels to Stockholm using the PoC at transitous.org

I'm getting this result, I think the hours parts get truncated away (I guess it should be 23h 33min)

![Skärmbild från 2024-02-23 07-56-00](https://github.com/motis-project/motis/assets/373874/3ddb9139-121d-44aa-8799-1e169cfa33e7)

**Comment by felixguendling** [comment]
Hey :wave:

Thank you for your report! 😃 

We're planning to create a new (mobile-first) UI since the old UI is written in the Elm programming language which is effectively discontinued (and the code became unmaintainable due to some disadvantages of Elm). So we stopped making changes to the UI to save resources. However, feel free to provide a fix PR.
