### ISSUE TITLE
Somewhat weird routing results around Riga train station

### ISSUE THREAD

**Issue by jbruechert** [motis-project/motis#544]
![Screenshot_20240914-183613_KDE Itinerary](https://github.com/user-attachments/assets/f2f337ce-ff85-48c4-b99c-3883c1b5f798)

![Screenshot_20240914-185542_KDE Itinerary](https://github.com/user-attachments/assets/c3028012-6be3-48ba-9cd0-286b843a65f0)

![Screenshot_20240914-185551_KDE Itinerary](https://github.com/user-attachments/assets/f3b55127-92d5-4c12-a253-175425ab855d)

The results should be reproducible on routing.spline.de.

The feeds for Lithuania, Latvia and flixbus europe from https://transitous.org/sources/ should be enough for reproducing it locally.

**Comment by felixguendling** [comment]
Do you have the JSON response with the stations IDs? Looks like the first osr foot routing didn't find a connection directly to the Riga Bus Station and since we disabled combining osr footpaths with timetable footpaths, there's no other option than to do a loop. One option would be to enable timetable footpaths at the after (or before, at the destination) osr footpaths - but this can lead to quite long combined osr + timetable footpaths (total length = maximum osr footpath duration given in the query + maximum footpath length in the timetable). This is also something an API user would probably not expect.

**Comment by felixguendling** [comment]
My guess is that this was a station start (no coordinates) and for this case, the `use_start_footpaths` option was off. I changed this in [v0.12.14](https://github.com/motis-project/motis/releases/tag/v0.12.14).
