### ISSUE TITLE
Timezone problem in Web UI

### ISSUE THREAD

**Issue by matteoferrux** [motis-project/motis#547]
Hi,
I have installed my own instance of MOTIS (and how wonderful is it!) and when I make a search I always have a difference of two hours between the search and the results. 

![image](https://github.com/user-attachments/assets/f73e8e62-bcd1-46c1-95dd-6ddc3f837b62)

I've already set default_timezone in Nigiri
![image](https://github.com/user-attachments/assets/faafae4a-4568-4b6e-89c7-9d8b2f417300)

Do you have a solution ?
Thanks !

**Comment by felixguendling** [comment]
The reason is that the UI tries to provide an overview of a time interval.

Currently, the initial query time interval is `[t-1h, t+1h]`, so 1h around the time you gave to it:
https://github.com/motis-project/motis/blob/577da282f3703b59675aafd46fd61f942f9683cc/ui/web/src/Data/Routing/Request.elm#L24-L43

If the initial interval doesn't contain `min_connection_count` connections, the interval will be extended in both directions (earlier + later).

We're working on a new UI where the logic is a little bit different: it will also give you an interval, however the interval will start at the time you provided in case it's a departure time. If it's an arrival time it will end at this time.

Since the current UI is deprecated, I won't put any effort to improve it in order to be able to focus on the new UI. If anyone wants to replicate the logic of the new UI into the old, I am open to merge PRs. Just beware that this UI will be replaced.

**Comment by felixguendling** [comment]
Ah. Maybe I should've started with: "That's currently the expected behavior"
(but the next version of the UI has it already fixed from the beginning)

**Comment by felixguendling** [comment]
At least for search by departure time, the new MOTIS v2 UI should solve this problem. For search by arrival time, we would've to sort by arrival time to show the connection closest to the time given by the user. This is currently not the case but should maybe be implemented (?).

**Comment by felixguendling** [comment]
As discussed in the matrix room: sorting or scrolling to the appropriate connection (closest to the user provided time) can be done on the client.
