### ISSUE TITLE
Extremely high walking time estimates if no path can be found

### ISSUE THREAD

**Issue by jbruechert** [motis-project/motis#548]
This is a bit of a special case because there is a border here, but it is also reproducible when starting from a building that is located to far from a street.
I just haven't found another place to reproduce it without doxing myself.

The path that is estimated to take 18h is about 4km long and Graph Hopper estimates 0:46 instead.

Copy pastable coordinate for reproducing: `45.153385;19.177957`

![image](https://github.com/user-attachments/assets/c8d50177-be95-4123-a022-16ca8cdd2e26)
![image](https://github.com/user-attachments/assets/1485af6b-1919-47c4-a611-5afdd6250083)

**Comment by felixguendling** [comment]
This 18h footpath seems to occur again..
It was already discussed here (where I also explain my reasoning what's going on):
https://github.com/motis-project/motis/discussions/534#discussioncomment-10285513

I was hoping to fix it here:
https://github.com/motis-project/motis/pull/542/commits/193d4c2ceb672786d1de98fb09e63b2ac70a8c03#diff-8d9c8cd9c89caa1b2f03cc19b9209ab104fe47b2f43b44247ea60926a5a75e19R200-R202

But obviously, I didn't find the right spot.

Should already be fixed with MOTIS 2.0 because there "unreachable" is expressed as `std::nullopt`.

**Comment by felixguendling** [comment]
Fixed with v2
